# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-04 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='姓名')),
                ('content', models.CharField(max_length=1000, verbose_name='内容')),
                ('name_pf', models.CharField(max_length=30, null=True, verbose_name='电影评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='视频名称')),
                ('short_desc', models.CharField(max_length=30, verbose_name='集数')),
                ('tags', models.CharField(max_length=30, verbose_name='类型')),
                ('director', models.CharField(max_length=20, verbose_name='导演')),
                ('stars', models.CharField(max_length=100, verbose_name='主演')),
                ('description', models.CharField(max_length=1000, verbose_name='简介')),
                ('play_time', models.CharField(max_length=10, verbose_name='时长')),
                ('img', models.CharField(max_length=200, verbose_name='图片路径')),
                ('hot', models.CharField(max_length=10, verbose_name='热度播放量')),
                ('score', models.CharField(max_length=30, null=True, verbose_name='分数')),
                ('play_url', models.CharField(max_length=100, null=True, verbose_name='播放路径')),
                ('alias', models.CharField(max_length=30, null=True, verbose_name='别名')),
                ('lx', models.CharField(max_length=30, verbose_name='种类')),
            ],
            options={
                'verbose_name': '视频文件',
                'verbose_name_plural': '视频文件',
                'db_table': 'plays',
            },
        ),
        migrations.CreateModel(
            name='Playurls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_name', models.CharField(db_index=True, max_length=30, verbose_name='视频名称集数')),
                ('play_url', models.CharField(max_length=100, verbose_name='视频地址')),
            ],
            options={
                'verbose_name': '视频文件地址',
                'verbose_name_plural': '视频文件地址',
                'db_table': 'playurls',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='姓名')),
                ('img', models.CharField(max_length=200, verbose_name='图片路径')),
                ('playname', models.CharField(max_length=30, verbose_name='视频名称')),
                ('name_pf', models.CharField(max_length=30, verbose_name='用户评分')),
            ],
            options={
                'verbose_name': '播放记录',
                'verbose_name_plural': '播放记录',
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='用户名')),
                ('file', models.FileField(upload_to='./upload/', verbose_name='上传的文件')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'db_table': 'upload',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(db_index=True, max_length=30, verbose_name='用户名')),
                ('uphone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('upwd', models.CharField(max_length=100, verbose_name='密码')),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
